services:
  api:
    build: .
    ports:
      - "3005:3000"
    volumes:
      - ./models:/app/models
      - ./.cache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - vllm-network

networks:
  vllm-network:
    driver: bridge

volumes:
  models:
