services:
  management-api:
    build: ./management-api
    ports:
      - "8080:8080" 
    volumes:
      - ./models:/models
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped

volumes:
  models: